[tool.poetry]
name = "easymatch"
version = "0.1.0"
description = "Minimal, layman-readable string pattern matching."
authors = ["Thomas Feldmann <mail@tfeldmann.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
flit = "^3.2.0"
pytest = "^6.2.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
